# Install pre-commit hooks via
# pre-commit install

repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        files: ^.*\.(py|c|h|md|Rmd|yml)$
        args: ["--write-changes", "--ignore-words", ".codespellignore" ]
